/*Japanese Cities : Query to filter Japanese City*/

create database celebal;
use celebal;

CREATE TABLE CITY (
    ID INT,
    NAME VARCHAR(17),
    COUNTRYCODE VARCHAR(3),
    DISTRICT VARCHAR(20),
    POPULATION INT
);

INSERT INTO CITY (ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) 
VALUES (1001, 'Mumbai', 'IND', 'Maharashtra', 12442373);

INSERT INTO CITY (ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) 
VALUES (1002, 'Tokyo', 'JPN', 'Tokyo', 13929286);

INSERT INTO CITY (ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) 
VALUES (1003, 'Delhi', 'IND', 'Delhi',29000000);

SELECT * 
FROM CITY 
WHERE COUNTRYCODE = 'JPN';