/*Select By ID : SQL query to fetch details by ID*/

create database celebal;
use celebal;

CREATE TABLE CITY (
    ID INT,
    NAME VARCHAR(17),
    COUNTRYCODE VARCHAR(3),
    DISTRICT VARCHAR(20),
    POPULATION INT
);

INSERT INTO CITY (ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) 
VALUES (1661, 'Panipat', 'IND', 'Haryana', 294292);

INSERT INTO CITY (ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) 
VALUES (1001, 'Mumbai', 'IND', 'Maharashtra', 12442373);

INSERT INTO CITY (ID, NAME, COUNTRYCODE, DISTRICT, POPULATION) 
VALUES (1002, 'Tokyo', 'JPN', 'Tokyo', 13929286);

SELECT * FROM CITY WHERE ID = 1661;